import React, { useState, useEffect } from "react";
import { Layout } from "@/components/Layout";
import { 
  Play, 
  Download, 
  Share2, 
  Filter, 
  Search, 
  Video, 
  MonitorPlay,
  User
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Skeleton } from "@/components/ui/skeleton";
import { supabase } from "@/integrations/supabase/client";

export default function HighlightsPage() {
  const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [activeHighlight, setActiveHighlight] = useState<any | null>(null);
  const [clips, setClips] = useState<any[]>([]);

  useEffect(() => {
    const fetchClips = async () => {
      setLoading(true);
      // Currently, highlights are derived from play_by_play events that have video_url
      const { data, error } = await supabase
        .from("play_by_play")
        .select(`
          *,
          games!inner(
            home_team:teams!games_home_team_id_fkey(name),
            away_team:teams!games_away_team_id_fkey(name)
          )
        `)
        .not("video_url", "is", null)
        .order("created_at", { ascending: false });

      if (!error && data) {
        setClips(data);
      }
      setLoading(false);
    };

    fetchClips();
  }, []);

  const filteredHighlights = clips.filter(h => {
    const matchesFilter = filter === "all" || h.event_type?.toLowerCase().includes(filter.toLowerCase());
    const matchesSearch = h.player_name?.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          h.event_description?.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  return (
    <Layout title="Game Highlights | CourtVision Elite">
      <div className="space-y-8 pb-10">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="border-primary/50 text-primary font-mono text-[10px] uppercase tracking-widest px-2">
                AI Pipeline: Online
              </Badge>
              <Badge variant="outline" className="border-accent/50 text-accent font-mono text-[10px] uppercase tracking-widest px-2">
                Modal.com A100 Managed
              </Badge>
            </div>
            <h1 className="text-4xl font-bold flex items-center gap-3">
              <MonitorPlay className="h-8 w-8 text-primary" />
              Highlights Hub
            </h1>
            <p className="text-muted-foreground max-w-xl">
              Tactical video analysis generated by your GPU processing pipeline. Review every made shot, block, and defensive rotation.
            </p>
          </div>
          
          <div className="flex flex-wrap items-center gap-3">
            <div className="relative w-full sm:w-64">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input 
                placeholder="Search player or play..." 
                className="pl-9 bg-card/50 border-border"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <Select value={filter} onValueChange={setFilter}>
              <SelectTrigger className="w-full sm:w-44 bg-card/50 border-border">
                <Filter className="h-4 w-4 mr-2 text-muted-foreground" />
                <SelectValue placeholder="Action Type" />
              </SelectTrigger>
              <SelectContent className="bg-card border-border">
                <SelectItem value="all">All Actions</SelectItem>
                <SelectItem value="made_shot">Made Shots</SelectItem>
                <SelectItem value="missed_shot">Missed Shots</SelectItem>
                <SelectItem value="block">Blocks</SelectItem>
                <SelectItem value="steal">Steals</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* Featured Clip Area */}
        {activeHighlight && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 animate-in fade-in slide-in-from-top-4 duration-500">
            <div className="lg:col-span-2 space-y-4">
              <div className="rounded-2xl overflow-hidden border border-border bg-black shadow-2xl">
                <AspectRatio ratio={16 / 9}>
                  <div className="w-full h-full flex items-center justify-center bg-zinc-900 text-muted-foreground group relative">
                    {activeHighlight.video_url ? (
                      <video 
                        src={activeHighlight.video_url} 
                        controls 
                        className="w-full h-full object-contain"
                        autoPlay
                      />
                    ) : (
                      <div className="absolute inset-0 flex items-center justify-center">
                        <p className="text-sm font-mono">Loading Video Stream...</p>
                      </div>
                    )}
                  </div>
                </AspectRatio>
              </div>
            </div>
            <div className="space-y-6">
              <Card className="bg-card/50 border-border h-full">
                <CardHeader>
                  <div className="flex justify-between items-start">
                    <Badge className="bg-primary/20 text-primary border-primary/30 uppercase text-[10px] tracking-widest">
                      {activeHighlight.event_type?.replace('_', ' ')}
                    </Badge>
                    <span className="text-[10px] font-mono text-muted-foreground">{activeHighlight.game_time}</span>
                  </div>
                  <CardTitle className="text-2xl mt-2">{activeHighlight.event_description}</CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="flex items-center gap-4 p-4 rounded-xl bg-muted/30 border border-border/50">
                    <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20">
                      <User className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <p className="text-sm font-bold">{activeHighlight.player_name}</p>
                      <p className="text-xs text-muted-foreground">
                        {activeHighlight.games?.home_team?.name} vs {activeHighlight.games?.away_team?.name}
                      </p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <Button variant="outline" className="w-full border-border bg-muted/50 hover:bg-muted text-xs gap-2">
                      <Download className="h-3 w-3" /> Save Clip
                    </Button>
                    <Button variant="outline" className="w-full border-border bg-muted/50 hover:bg-muted text-xs gap-2">
                      <Share2 className="h-3 w-3" /> Share
                    </Button>
                  </div>

                  <div className="pt-6 border-t border-border space-y-3">
                    <p className="text-[10px] uppercase tracking-widest text-muted-foreground font-bold">Metadata</p>
                    <div className="flex items-center justify-between text-xs">
                      <span className="text-muted-foreground">Inference Model</span>
                      <span className="font-mono text-accent">YOLOv11m-BASKETBALL</span>
                    </div>
                    <div className="flex items-center justify-between text-xs">
                      <span className="text-muted-foreground">Processed At</span>
                      <span className="text-foreground">{new Date(activeHighlight.created_at).toLocaleDateString()}</span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        )}

        {/* Highlight Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {loading ? (
            Array(8).fill(0).map((_, i) => (
              <div key={i} className="space-y-3">
                <Skeleton className="h-40 w-full rounded-xl bg-muted/50" />
                <Skeleton className="h-4 w-3/4 bg-muted/50" />
                <Skeleton className="h-4 w-1/2 bg-muted/50" />
              </div>
            ))
          ) : filteredHighlights.length > 0 ? (
            filteredHighlights.map((highlight) => (
              <Card 
                key={highlight.id} 
                className={`group border-border bg-card/40 hover:bg-card/60 transition-all cursor-pointer overflow-hidden ${activeHighlight?.id === highlight.id ? 'ring-2 ring-primary border-transparent' : ''}`}
                onClick={() => setActiveHighlight(highlight)}
              >
                <div className="relative">
                  <AspectRatio ratio={16 / 9}>
                    <div className="w-full h-full bg-zinc-900 flex items-center justify-center border-b border-white/5">
                      <Video className="h-10 w-10 text-muted-foreground/30 group-hover:scale-110 transition-transform" />
                    </div>
                  </AspectRatio>
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <div className="h-10 w-10 rounded-full bg-primary flex items-center justify-center shadow-lg">
                      <Play className="h-5 w-5 text-white fill-white ml-0.5" />
                    </div>
                  </div>
                  <div className="absolute bottom-2 right-2">
                    <Badge className="bg-black/60 backdrop-blur-md border-none text-[10px] py-0 px-2 font-mono">
                      {highlight.game_time}
                    </Badge>
                  </div>
                </div>
                <CardContent className="p-4 space-y-2">
                  <div className="flex justify-between items-start gap-2">
                    <p className="text-sm font-bold truncate">{highlight.player_name}</p>
                    <Badge variant="outline" className="text-[9px] uppercase tracking-tighter border-border bg-muted/50">
                      {highlight.event_type?.toUpperCase().replace('_', ' ')}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground truncate">{highlight.event_description}</p>
                </CardContent>
              </Card>
            ))
          ) : (
            <div className="col-span-full py-20 text-center space-y-4">
              <div className="h-20 w-20 rounded-full bg-muted/30 flex items-center justify-center mx-auto">
                <Video className="h-10 w-10 text-muted-foreground" />
              </div>
              <div>
                <h3 className="text-xl font-bold">No highlights found</h3>
                <p className="text-muted-foreground">Adjust your filters or process a new game to generate clips.</p>
              </div>
              <Button onClick={() => window.location.href = '/'} variant="outline" className="border-primary text-primary hover:bg-primary/10">
                Go to Dashboard
              </Button>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
}