// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read from environment variables and trim whitespace to prevent ERR_NAME_NOT_RESOLVED
const SUPABASE_URL = (process.env.NEXT_PUBLIC_SUPABASE_URL || "").trim();
const SUPABASE_PUBLISHABLE_KEY = (process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "").trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Only log error on client-side to prevent server-side noise during build
  if (typeof window !== "undefined") {
    console.error('Missing Supabase environment variables. Check Vercel Settings.');
  }
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co', 
  SUPABASE_PUBLISHABLE_KEY || 'placeholder'
);